# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - darwin
      - linux
    ignore:
      - goos: linux
        goarch: '386'
    main: ./cmd/
    ldflags:
      - -s -w
      - -X github.com/touchardv/argocd-offline-cli/cmd/commands.version={{.Version}}
      - -X github.com/touchardv/argocd-offline-cli/cmd/commands.commit={{.Commit}}
      - -X github.com/touchardv/argocd-offline-cli/cmd/commands.date={{.Date}}
